openapi: 3.0.0
info:
  title: Outfit Public API
  description: On-brand production at scale.
  contact:
    name: Outfit
    email: tech@outfit.io
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  version: 3.1.0
servers:
  - url: 'https://{subdomain}.outfit.io/api/v3'
    description: ''
    variables:
      subdomain:
        description: Subdomain used for account.
        default: outfit
tags:
  - name: Session
    description: >-
      Begin your API session here. Use the session endpoint to authenticate an
      API session with the Outfit Public API. Outfit API sessions are valid for
      8 hours.
  - name: Manage teams
    description: Create new teams and sync team metadata with Outfit.
