theme:
  colors:
    primary:
      main: '#32329f'
  typography:
    fontFamily: 'Noto Sans, sans-serif'
    fontSize: "14px"
    lineHeight: '20px'
    headings:
      fontFamily: 'Open Sans'
      fontWeight: '700'
      lineHeight: '28px'